### ISSUE TITLE
Docker Compose for Portainer?

### ISSUE THREAD

**Issue by TechnoMaverick** [kieraneglin/pinchflat#105]
Hello! Super interested in the project, it looks way more simple than what I've been using currently.

I'm pretty new to self hosting and I use Portainer to deploy services, with docker compose. I was looking over how to set up Pinchflat and wasn't sure how to do that like I normally would. It's possible that I'm missing how to go about it, but if not, is there a chance that a compose file could be made? I'm not sure how difficult that is, and if it's not of interest to the project, that's okay!

I use a NUC for a server, if that matters.

Thanks!

**Comment by kieraneglin** [comment]
Hey there! Thanks for the interest (:

I've never used Portainer, but I'm roughly familiar with the idea. The Pinchflat Docker image is quite simple and entirely self-contained. docker-compose absolutely could be used here, but you might be able to use the container directly as outlined [here](https://docs.portainer.io/user/docker/containers). It looks like you'll need to manually map your ports and volumes, but it seems doable!

There _is_ a Docker compose file, but it's for development and not suitable for deployment. I'll look into what it'd take to add better support sometime this weekend 🤙🏻

**Comment by kieraneglin** [comment]
```
version: '3'
services:
  pinchflat:
    image: keglin/pinchflat:latest
    ports:
      - '8945:8945'
    volumes:
      - /your/config/path:/config
      - /your/download/path:/downloads
```

Does that help at all? Full disclosure, I typed this out from memory on my phone so there's almost certainly a mistake somewhere there. If it does work, don't forget to replace the volume paths volumes on your machine!

**Comment by tiritibambix** [comment]
If that can help, from the [docker setup](https://github.com/kieraneglin/pinchflat?tab=readme-ov-file#docker) segment of the doc, you can use [composerize](https://www.composerize.com/) to convert the docker CLi to docker-compose.
This
```
docker run \
  -p 8945:8945 \
  -v /host/path/to/config:/config \
  -v /host/path/to/downloads:/downloads \
  keglin/pinchflat:latest
```
Will return this
```
name: <your project name>
services:
    pinchflat:
        ports:
            - 8945:8945
        volumes:
            - /host/path/to/config:/config
            - /host/path/to/downloads:/downloads
        image: keglin/pinchflat:latest
```

Help me a lot when I started hosting

**Comment by kieraneglin** [comment]
@TechnoMaverick Would you mind letting me know if that worked out for you? If so, I'll add that to the README!

**Comment by gelof2022** [comment]
Dockage converts docker run into docker compose.

**Comment by kieraneglin** [comment]
@TechnoMaverick you should still be able to run the commands I recommended in #106. In your case, you'd want to run these commands on the _host_ machine: `chmod -R 755 /pinchflat-config /media/Shogun/Data/yt-pinchflat` and `chown -R nobody /pinchflat-config /media/Shogun/Data/yt-pinchflat`. 

Then, you may have to add the `user` line to your docker-compose:

```yaml
version: '3'
services:
  pinchflat:
    image: keglin/pinchflat:latest
    user: '99:100'
    ports:
      - '8945:8945'
    volumes:
      - /pinchflat-config:/config
      - /media/Shogun/Data/yt-pinchflat:/yt-pinchflat
```

**Comment by gelof2022** [comment]
I got it running on Synology.

This is my compose:

```
version: "3.3"
services:
  pinchflat:
    ports:
      - 8945:8945
    environment:
      - TZ = Australia/Sydney
    volumes:
      - /volume1/docker/pinchflat/config:/config
      - /volume1/docker/pinchflat/downloads:/downloads
    image: keglin/pinchflat:latest
    user: '1030:100'
networks: {}
```
I also had to make my user (id 1030) own the /docker/pinchflat/, /docker/pinchflat/config & /docker/pinchflat/downloads directories using File Station.
