### ISSUE TITLE
[FR] Support for reverse proxy

### ISSUE THREAD

**Issue by Ogglord** [kieraneglin/pinchflat#275]
I would like to try this, but I must run all my docker containers through a reverse proxy. Traefik is what I'm using but that's irrelevant for the feature request.

**Describe the solution you'd like**
A way to set the hostname/base url using config. And any additional tweaks required that I might have overseen.
I'd like to access the service using **mydomain.com/pinchflat**. I guess that this requires the baseurl to be **/pinchflat** instead of / (as defined in the routers.ex (lib/pinchflat_web/router.ex).

**Describe alternatives you've considered**
Using a subdomain pinchflat.mydomain.com is probably going to work.

**Additional context**
Let me know if I can help

**Comment by Ogglord** [comment]
Sure, I can test it. Gimme an hour

**Comment by Ogglord** [comment]
It fails with this in the log:
```
20:02:21.276 request_id=F9RWNHdoqBkhp7cAAB9i [info] GET /pinchflat
20:02:21.277 request_id=F9RWNHdoqBkhp7cAAB9i [info] Sent 404 in 413µs
20:02:21.277 request_id=F9RWNHdoqBkhp7cAAB9i [debug] Converted error Phoenix.Router.NoRouteError to 404 response
```
docker-compose.yml
```
  pinchflat:
    image: keglin/pinchflat:dev
    environment:
      - TZ=Europe/Stockholm
      - BASE_ROUTE_PATH=/pinchflat
    volumes:
      - ${CONFIG_ROOT:-.}/pinchflat:/config
      - nas_youtube:/downloads   
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8945/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    labels:
      - traefik.enable=true
      - traefik.http.routers.pinchflat.rule=(Host(`${HOSTNAME}`)&& PathPrefix(`/pinchflat`))
      - traefik.http.routers.pinchflat.tls=true
      - traefik.http.routers.pinchflat.tls.certresolver=myresolver
      - traefik.http.services.pinchflat.loadbalancer.server.port=8945
```
