### ISSUE TITLE
Question: How to use Nginx reverse proxy?

### ISSUE THREAD

**Issue by starlingfire** [kieraneglin/pinchflat#332]
I'm running Nginx Proxy Manager and setting it up the same way I've set up everything else doesn't work. 

I can access the service fine using my local IP: http://192.168.1.240:8945, so I add that as a Proxy Host record in NPM:
![image](https://github.com/user-attachments/assets/c189657e-fa63-4092-9dee-1f191162ed1c)

I haven't set the `BASE_ROUTE_PATH` or any other configs outside the volumes. 

Running with the following docker compose:

```
pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=info
    ports:
      - 8945:8945
    volumes:
      - ./pinchflat:/config
      - /mnt/storage/Youtube:/downloads 
```

I am using my PiHole as the DNS resolver, which is directing requests from `pinchflat.lan` to my local IP. 

Is there something I'm missing?

**EDIT** it must be on my end, because I can access it from my phone on the wifi, but not my PC. I'll investigate my DNS settings there. I'll close this now.
