### ISSUE TITLE
[FR] Global yt-dlp options

### ISSUE THREAD

**Issue by ASMfreaK** [kieraneglin/pinchflat#348]
**Is your feature request related to a problem? Please describe.**
I want an ability to add a global yt-dlp argument (namely - `--proxy`). Without it pinchflat fails to pass though onboarding.
FYI - setting the same option in a config file (base.....txt) as per docs does not affect the onboarding process.

**Describe the solution you'd like**
Env variable with this setting would be nice

**Describe alternatives you've considered**
For the moment, I've patched the container like this:

```Dockerfile
# file Dockerfile
FROM ghcr.io/kieraneglin/pinchflat:latest
COPY yt-dlp /yt-dlp
RUN \
        mv /usr/local/bin/yt-dlp /opt/yt-dlp && \
        mv /yt-dlp /usr/local/bin/yt-dlp && \
        chmod +x /usr/local/bin/yt-dlp

```

```bash
#!/bin/bash
# file yt-dlp
exec /opt/yt-dlp --proxy PROXY_URL "$@"
```

**Comment by AlexFullmoon** [comment]
I think this deserves mention in docs somewhere anyway.

---

To whomever this may concern with regard to current situation in Russia, here's example compose file for pinchflat with byedpi. 

```yml
version: '3'

services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    user: '1000:100'
    ports:
      - 8945:8945
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /path/to/config/data:config
      - /path/to/media:/downloads
      - /path/to/config/yt-dlp-global.conf:/yt-dlp.conf
  # in conf file: --proxy socks5://dpi:1080

  dpi:
    image: tazihad/byedpi
    container_name: pinchflat-dpi
    expose: 
      - 1080
    command: --disorder 1 --fake 0 --ttl 1 --auto=torst --tlsrec 1+s --debug 1
    restart: unless-stopped
```
