### ISSUE TITLE
[Triage] Internal Server Error

### ISSUE THREAD

**Issue by primez** [kieraneglin/pinchflat#400]
**Describe the bug**
Hello. On the home page I see an error message that doesn't go away even after container restarts. It appeared just after I set up a source and a media profile. I was following the guide from the documentation.
Thank you for looking into this.

Here is the message
```
**Status**:
`500`

**Reason**:
`%FunctionClauseError{module: Calendar, function: :strftime, arity: 3, kind: nil, args: nil, clauses: nil}`

**Stacktrace**:
    (elixir 1.17.0) lib/calendar.ex:575: Calendar.strftime({:error, :time_zone_not_found}, "%Y-%m-%d %H:%M", [])
    (pinchflat 2024.9.12) lib/pinchflat_web/components/custom_components/text_components.ex:94: anonymous fn/2 in PinchflatWeb.CustomComponents.TextComponents."datetime_in_zone (overridable 1)"/1
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:391: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.17.0) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:571: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_comprehension/5
    (elixir 1.17.0) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3

```
I also attached a file with logs to this issue.

Here is a docker compose piece that I used:
```
services:
  # Youtube downloader
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    networks:
      - t3_proxy
      - default
    security_opt:
      - no-new-privileges:true
    profiles: ["media", "all"]
    restart: unless-stopped
    environment:
      # Set the timezone to your local timezone
      - TZ=$TZ
      - LOG_LEVEL=debug
    ports:
      - '8945:8945'
    volumes:
      - $DOCKERDIR/appdata/pinchflat:/config
      - $USERDIR/downloads/youtube:/downloads
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.pinchflat-rtr.entrypoints=websecure"
      - "traefik.http.routers.pinchflat-rtr.rule=Host(`pinchflat.$DOMAINNAME_HS`)"
      ## Middlewares
      - "traefik.http.routers.pinchflat-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.pinchflat-rtr.service=pinchflat-svc"
      - "traefik.http.services.pinchflat-svc.loadbalancer.server.port=8945"
```

**To Reproduce**

1. Spin up a container according to the docker compose file
2. Add a media profile for Jellyfin
3. Add a source - a link to a single playlist

**Expected behavior**
No exceptions

**Screenshots**
![image](https://github.com/user-attachments/assets/957cde4c-c991-428a-82f4-4001893172cc)

**Diagnostic info**
```
- App Version: 2024.9.12
- yt-dlp Version: 2024.08.06
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: Europe/Kyiv
```

**Additional context**
[pinchflat-logs-2024-09-28.txt](https://github.com/user-attachments/files/17174276/pinchflat-logs-2024-09-28.txt)
