### ISSUE TITLE
[Triage] Unable to send test notification

### ISSUE THREAD

**Issue by harupong** [kieraneglin/pinchflat#419]
[Triage] Unable to send test notification

**Describe the bug**
First and foremost, thank you so much for creating such a useful app!! Your app was mentioned on [Self\-Hosted 134: YouTube Unplugged](https://selfhosted.show/134), and I’m so glad that I tried it out. It’s working so smoothly so far.

One small thing I noticed while trying out is that the test notification didn’t show up, but the actual notification DID show up. If it’s just me, then please close this issue.

**To Reproduce**

1. Go to config -> settings
2. paste Slack webhook url(“as is”)
3. click "send test" icon
4. test notification not showing up on Slack

**Expected behavior**
Test notificaion coming in through apprise to Slack

**Diagnostic info**

- App Version: 2024.10.2
- yt-dlp Version: 2024.09.27
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: Asia/Tokyo

<img width="886" alt="image" src="https://github.com/user-attachments/assets/0ecb47df-3c06-48ce-b303-9a11b82ed5c9">

This is a Slack screenshot of me  successfully setting up webhook on Pinchflat, test notification was sent but not recieved, and the acutual notification did show up.

**Additional context**
I’m using `docker compose`, and my compose.yml is as follows:

```
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./config:/config
      - /mnt/nas/public:/downloads
    restart: unless-stopped
```
