### ISSUE TITLE
[Triage] Unable to connect to SMB downloads folder

### ISSUE THREAD

**Issue by rymccue** [kieraneglin/pinchflat#426]
**Describe the bug**
I have been using Pinchflat for a while and it has been great. I had it working fine but since switching to the downloads being on an SMB share I have been unable to run the application. I have done a ton of debugging with no luck, and it appears that the share is setup correctly since when I change the docker compose entrypoint to `ls -la /downloads` and `touch` a file on the SMB share, and it is able to create the file.

I've tried using `user: "root"` and `user: "99:100"`, along with the chmod commands and messing with the smb `driver_opts`. I am not entirely sure what else I can do given I am able to successfully view and write to the `/downloads` folder from inside the container.

I am sure there is a small, silly thing I'm missing, but in a few sessions of trying to debug it over the past week I've come up with nothing :sweat_smile: 

**Expected behavior**
When I run Pinchflat, it Docker container does not crash.

**Screenshots**

**Diagnostic info**

Unable to get into the app.

**Additional context**

Docker compose:
```
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      - TZ=America/Edmonton
    user: "65534:1000"
    # entrypoint: sh -c "ls -la /downloads/shows && ls -la /config && id && touch /downloads/shows/abcd.txt"
    volumes:
      - /path/to/pinchflat/config:/config
      - smb-youtube-drive:/downloads
      
volumes:
  tailscale:
  smb-youtube-drive:
    driver_opts:
      type: cifs
      o: "username=user,password=password,uid=65534,gid=1000"
      device: //nas/media/youtube
```

Docker logs:
```
2024-10-22 17:06:44.088 [info] | Checking permissions for /config
2024-10-22 17:06:44.092 [info] | Permissions OK
2024-10-22 17:06:44.092 [info] | Checking permissions for /downloads
2024-10-22 17:06:44.094 [error] | The directory "/downloads" is not writeable by the Docker container.
Please ensure that the directory exists and is writeable by the Docker
container. All setups are different, but you may be able to run something
like this on the *host*:
  chown nobody -R <host path that maps to /downloads>
  chmod 755 -R <host path that maps to /downloads>
Swapping in your real host path. Then, you should set the user running
this container by editing your `docker run` command like so:
    docker run --user 99:100 <rest of the command>
Or adding `user: '99:100'` to the Pinchflat service of your Docker Compose
file. Again, there are many ways to do this depending on your setup and
this is just one example. See issue #106 in the Pinchflat Github for more.
No matter the case, this _is_ a permissions error and allowing the container
to write to the directory is the only way to fix it. It is not recommended
to run the container as `root` because files created by Pinchflat may not
be accessible to other apps that want to modify them.
** (RuntimeError) Permission denied
    (pinchflat 2024.10.2) lib/pinchflat/release.ex:51: anonymous fn/1 in Pinchflat.Release.check_file_permissions/0
    (elixir 1.17.0) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    nofile:1: (file)
    (stdlib 5.2.3) erl_eval.erl:750: :erl_eval.do_apply/7
    (elixir 1.17.0) lib/code.ex:572: Code.validated_eval_string/3
Filesystem error. Exiting.
```

Logs when running test entrypoint (`ls -la /downloads/shows && ls -la /config && id && touch /downloads/shows/abcd.txt`):
```
total 48
drwxr-xr-x 2 nobody 1000     0 Oct 22 16:50 .
drwxr-xr-x 2 nobody 1000     0 Oct 14 19:35 ..
-rwxr-xr-x 1 nobody 1000     0 Oct 22 16:56 abcd.txt
drwxr-xr-x 2 nobody 1000     0 Oct 14 19:36 Channel 1
drwxr-xr-x 2 nobody 1000     0 Oct 14 19:37 Channel 2
-r-xr-xr-x 1 nobody 1000 20484 Oct 14 19:35 .DS_Store

total 24
drwxr-xr-x 6 nobody 1000 4096 Apr 11  2024 .
drwxr-xr-x 1 root   root 4096 Oct 22 17:13 ..
drwxr-xr-x 2 nobody 1000 4096 Oct 22 17:06 db
drwxr-xr-x 4 nobody 1000 4096 Oct 22 17:06 extras
-rwxr-xr-x 1 nobody 1000    0 Oct 22 17:06 .keep
drwxr-xr-x 2 nobody 1000 4096 Oct 22 17:06 logs
drwxr-xr-x 4 nobody 1000 4096 Apr 11  2024 metadata

uid=65534(nobody) gid=1000 groups=1000
```
