### ISSUE TITLE
[Triage] Permissions check failed /etc/yt-dlp

### ISSUE THREAD

**Issue by onedr0p** [kieraneglin/pinchflat#488]
**Describe the bug**

I tried upgrading from v2024.10.30 → v2024.11.27 however it failed with ...

```
❯ k logs pinchflat-85c7494d8c-ltqfz
2024-11-27 15:02:46.267 [info] | Checking permissions for /config
2024-11-27 15:02:46.270 [info] | Permissions OK
2024-11-27 15:02:46.270 [info] | Checking permissions for /downloads
2024-11-27 15:02:46.270 [info] | Permissions OK
2024-11-27 15:02:46.270 [info] | Checking permissions for /etc/yt-dlp
2024-11-27 15:02:46.276 [error] | Permissions check failed: {:error, :erofs}
** (RuntimeError) Unknown error
    (pinchflat 2024.11.27) lib/pinchflat/release.ex:57: anonymous fn/1 in Pinchflat.Release.check_file_permissions/0
    (elixir 1.17.0) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    nofile:1: (file)
    (stdlib 5.2.3) erl_eval.erl:750: :erl_eval.do_apply/7
    (elixir 1.17.0) lib/code.ex:572: Code.validated_eval_string/3
Filesystem error. Exiting.
```

**To Reproduce**

Deploy pinchflat as non-root user with read only root filesystem with the container. This can be done with Kubernetes as I am doing below with the `securityContext` or with docker-compose with the `read_only: true` and `user` options.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  generation: 13
  labels:
    app.kubernetes.io/instance: pinchflat
    app.kubernetes.io/name: pinchflat
  name: pinchflat
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pinchflat
      app.kubernetes.io/name: pinchflat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pinchflat
        app.kubernetes.io/name: pinchflat
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: PORT
          value: "80"
        - name: TZ
          value: America/New_York
        - name: TZ_DATA_DIR
          value: /tmp/elixir_tz_data
        image: ghcr.io/kieraneglin/pinchflat:v2024.11.27@sha256:523cb30fc18282d7d5046ebea7a166a8ba67202e5d16d43e40dbea1bc36b10eb
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: app
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            gpu.intel.com/i915: "1"
            memory: 4Gi
          requests:
            cpu: 10m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /downloads
          name: downloads
        - mountPath: /media/Library/YouTube
          name: media
          subPath: Library/YouTube
        - mountPath: /tmp
          name: tmp
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
      restartPolicy: Always
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
        - 44
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pinchflat
      - emptyDir: {}
        name: downloads
      - name: media
        nfs:
          path: /mnt/eros/Media
          server: expanse.internal
      - emptyDir: {}
        name: tmp
```

**Expected behavior**

Not have a problem with permissions...

**Screenshots**

**Diagnostic info**

**Additional context**
