### ISSUE TITLE
Pinchflat bootup Error

### ISSUE THREAD

**Issue by Shoaib5136** [kieraneglin/pinchflat#529]
![image](https://github.com/user-attachments/assets/2b9b988c-2a70-452e-99a5-7ee7647982ab)

My docker compose:
version: '3'
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      # Set the timezone to your local timezone
      - TZ=Asia/karachi
       --user=99:100 #(Tried with 1000:1000 but no)
    ports:
      - '8945:8945'
    volumes:
      - /mnt/appdata/pinchflat/config:/config
      - /mnt/media/Youtube:/downloads
    restart: unless-stopped

How can I make it work?

**Comment by 56k-modem** [comment]
You have two unnecessary dashes (--) ahead of `user`. Try:

```
version: '3'
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
      environment:
    # Set the timezone to your local timezone
      - TZ=Asia/Karachi
    user=1000:1000
    ports:
      - '8945:8945'
    volumes:
      - /mnt/appdata/pinchflat/config:/config
      - /mnt/media/Youtube:/downloads
    restart: unless-stopped
```

Also make sure you have the proper permissions for your `/mnt/appdata/pinchflat` and `/mnt/media/Youtube` directories.
