### ISSUE TITLE
set BASE_ROUTE_PATH but got no route found error

### ISSUE THREAD

**Issue by chain710** [kieraneglin/pinchflat#592]
**Describe the bug**

set BASE_ROUTE_PATH=/pinchflat, visit http://example.com/pinchflat got following error
```
      reason: %Phoenix.Router.NoRouteError{
        plug_status: 404,
        message: "no route found for GET /pinchflat (PinchflatWeb.Router)",
        conn: %Plug.Conn{
          adapter: {Plug.Cowboy.Conn,
           %{
             pid: #PID<0.2526.0>,
             port: 80,
          (truncated)
```

docker compose:
```
  pinchflat:
    container_name: pinchflat
    image: ghcr.io/kieraneglin/pinchflat:v2025.1.17
    environment:
      # Set the timezone to your local timezone
      - TZ=Asia/Shanghai
      - BASE_ROUTE_PATH=/pinchflat
    ports:
      - '7033:8945'
    volumes:
      - /data/pinchflat/config:/config
      - /data/pinchflat/downloads:/downloads
```

nginx config
```
   location /pinchflat {
        include /etc/nginx/conf.d/auth/proxy.conf;
        proxy_pass http://pinchflat;
    }
```
