### ISSUE TITLE
[Triage] shorts not being excluded

### ISSUE THREAD

**Issue by shelldandy** [kieraneglin/pinchflat#612]
**Describe the bug**
Shorts are being downloaded even while excluded from the profile.

**To Reproduce**

Profile:

```
Raw Attributes

    id: 1
    name: YT Shows
    inserted_at: 2025-02-13T03:54:14Z
    updated_at: 2025-02-13T03:54:14Z
    output_path_template: /shows/{{ source_custom_name }}/{{ season_by_year__episode_by_date_and_index }} - {{ title }}.{{ ext }}
    sponsorblock_categories: sponsor, selfpromo
    sponsorblock_behaviour: remove
    download_thumbnail: true
    embed_thumbnail: true
    download_auto_subs: true
    download_subs: true
    embed_subs: true
    sub_langs: es, en
    preferred_resolution: 1440p
    download_metadata: true
    embed_metadata: true
    media_container:
    audio_track:
    download_nfo: true
    marked_for_deletion_at:
    download_source_images: true
    livestream_behaviour: exclude
    redownload_delay_days: 1
    shorts_behaviour: exclude

```

Added channel: https://www.youtube.com/@eugeniomonesma-documentales/

**Expected behavior**
Shorts to be excluded.

**Screenshots**

<img width="907" alt="Image" src="https://github.com/user-attachments/assets/b581114b-9f33-4e7c-a855-ce40e6b93b34" />

**Diagnostic info**

```
- App Version: 2025.1.27
- yt-dlp Version: 2025.01.26
- Apprise Version: v1.9.2
- System Architecture: x86_64-pc-linux-gnu
- Timezone: America/Mexico_City
```

**Additional context**
