### ISSUE TITLE
[Triage] Running container as non-root user breaks yt-dlp auto-update

### ISSUE THREAD

**Issue by agc93** [kieraneglin/pinchflat#625]
**Describe the bug**
If the container is run as a user other than `root`, the `yt-dlp` auto-update will fail as the user doesn't have write permissions to `/usr/local/bin/yt-dlp`

**To Reproduce**

With a Docker setup like the following:

```yaml
pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    user: 1000:1010
    env_file: env_file
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
    ports:
      - '8945:8945'
    volumes:
      - /path/to/config:/config
      - /path/to/media:/downloads
```

When Pinchflat attempts to update `yt-dlp` it fails:

```
pinchflat-1  | 2025-02-24 10:13:32.214 [info] | [command_wrapper]: /usr/local/bin/yt-dlp called with: --update
pinchflat-1  | ERROR: Unable to write to /usr/local/bin/yt-dlp; try running as administrator
pinchflat-1  | 2025-02-24 10:13:35.653 [error] | [command_wrapper]: /usr/local/bin/yt-dlp called with: --update exited: 100 with: Current version: stable@2025.01.26 from yt-dlp/yt-dlp
pinchflat-1  | Latest version: stable@2025.02.19 from yt-dlp/yt-dlp
pinchflat-1  | Current Build Hash: 227631e434d6f8418c4b821aeefc6302d3d1db1e7d805da2ad5b301c8d910107
pinchflat-1  | Updating to stable@2025.02.19 from yt-dlp/yt-dlp ...
```

**Expected behavior**

**Diagnostic info**

- App Version: 2025.2.20
- yt-dlp Version: 2025.01.26
- Apprise Version: v1.9.2
- System Architecture: x86_64-pc-linux-gnu
- Timezone: Australia/Brisbane
