### ISSUE TITLE
Nothing Pending Nothing Downloading

### ISSUE THREAD

**Issue by leadplasticmold** [kieraneglin/pinchflat#664]
Hello, I just installed this via docker compose. It looks potentially very cool. However, it doesn't seem to do anything once I add a media source. I'm very new to self hosting and still learning so any guidance would be appreciated. My docker compose file looks like this. 
```
version: '3'
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      # Set the timezone to your local timezone
      - TZ=America/New_York
    ports:
      - '8011:8945'
    volumes:
      - /home/servercat/pinchflat/config/:/config
      - /home/servercat/pinchflat/downloads:/downloads

```
And I grabbed the log file using the pinchflat GUI and attached it. Thank you for any help.
[pinchflat-logs-2025-03-18.txt](https://github.com/user-attachments/files/19328637/pinchflat-logs-2025-03-18.txt)
