### ISSUE TITLE
[FR] Disable File Permission Checks on /downloads

### ISSUE THREAD

**Issue by retrodaredevil** [kieraneglin/pinchflat#670]
**Is your feature request related to a problem? Please describe.**
There are numerous issues of users experiencing problems while booting up their application. I recently experienced the `The directory "/downloads" is not writeable by the Docker container.` error. However, I don't actually need write access to `/downloads`! I just need write access to certain directories within `/downloads`.

**Describe the solution you'd like**
Add an option to disable the check on the `/downloads` directory. Maybe a warning should be given when creating a profile that downloads to a directory without write permissionsi.

**Describe alternatives you've considered**
I could either mount the `/downloads` directory and make sure I actually have write permission, or I could run the container as root:root, but I wish to do neither.

**Additional context**
My docker compose is as follows:

```
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    restart: unless-stopped
    user: 127:133
    volumes:
      - /opt/containers/pinchflat/config:/config
      - /my/cool/path/yt-downloads:/downloads/yt-downloads
```

There is absolutely no reason that we need a check upon boot to make sure we have write permission to the `/downloads` directory. In my case, I know the container has write permission to `/downloads/yt-downloads`, but even still, the container will not boot up because of the check.
