### ISSUE TITLE
Documentation Addition: Guide for Adding Pinchflat to Gluetun Docker / Docker Compose Network

### ISSUE THREAD

**Issue by SJensen721** [kieraneglin/pinchflat#712]
Hey Pinchflat Team,

This is probably super obvious to everyone except for me, so I apologize, but _if_ there are others out there who it's not obvious to, it would be really helpful to have, very prominently displayed, a guide on how to set up Pinchflat inside an existing VPN network.

For example, many people who are going to be using Pinchflat are already going to be using similar tools like the arr's suite. They will, most likely, already have qBitTorrent set up, or some other torrenting thing set up. This will, in turn, have led them to setting up a VPN (generally through OpenVPN or Wireguard). A very common way of doing this is through a Gluetun docker compose stack, where you add the qbittorrent docker compose yaml to the bottom of the gluetun docker compose yaml and set the network_mode=service:gluetun for each subsequent docker compose yaml within the stack.

The benefits here are that youtube might not patrol European countries as much for IP violations (as many of those countries in Europe have very friendly piracy laws). In addition, VPN providers frequently cycle or spoof their IPs so that they can remain connected. This would really help a lot of users with Pinchflat because YouTube is cracking down on people (rate limiting). That, paired with "cookies.txt" providing a location for Google to think your browser is, might significantly reduce how many people are getting blocked/rate limited/banned.

Again, this was all not obvious to me - probably should have been, but wasn't. So, it may help someone else in the future and might help them create fewer issues or comments on issues (I commented on one because, it appears, I was rate limited, though the error from yt-dlp didn't seem to indicate it at first).

**Comment by SenorFusion** [comment]
Agreed! Since you have just completed this, would you be willing to write up the steps you took and post the compose file and some instructions?

This project is very open and welcoming to contributions

**Comment by MercifulCamel** [comment]
This is how mine looks.
```
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    network_mode: "container:gluetun"
    environment:
      # Set the timezone to your local timezone
      - TZ=Europe/Stockholm
#    ports:
#      - '8945:8945'
    volumes:
      - config:/config
      - downloads:/downloads

volumes:
  config:
    name: pinchflat-config
  downloads:
    name: pinchflat-dl
```
```
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=
      - VPN_TYPE=
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES=
      - SERVER_COUNTRIES=
      - OWNED_ONLY=
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - HEALTH_VPN_DURATION_INITIAL=6s
      - HEALTH_VPN_DURATION_ADDITION=10s
      - HEALTH_VPN_WAIT_DURATION=120s
      - DOT=OFF
    volumes:
      - wg:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8945:8945/tcp #pinchflat(ytdl)
volumes:
  wg:
    name: wg
```
